[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# PEP8相当（E/W）+ pyflakes(F), import整列(I), bugbear(B), 型(ANN), タイムゾーン(DTZ)
select = ["E", "W", "F", "I", "B", "UP", "D", "ANN", "DTZ"]
ignore = [
    "D203",      # Googleスタイルに合わせて調整
    "D213",      # multi-line-summary-second-line
    "ANN101",    # self の型注釈は不要
    "ANN102",    # cls の型注釈は不要
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
warn_unused_ignores = true
no_implicit_optional = true
strict_equality = true
