AWSTemplateFormatVersion: '2010-09-09'
Description: bemac-meeting-dev-secrets-stacks

### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Metadata                                                                                      ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "System Configuration"
        Parameters:
          - CustomerName
          - ProjectName
          - Environment
          - SystemName
      - Label:
          default: "Application Secrets (Leave empty to use existing values when updating)"
        Parameters:
          - AzureOpenAIApiKey
          - DatabaseUrl
          - AwsAccessKeyId
          - AwsSecretAccessKey

### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Parameters                                                                                    ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Parameters:
  CustomerName:
    Type: String
    Default: bemac

  ProjectName:
    Type: String
    Default: meeting

  Environment:
    Type: String
    Default: dev

  SystemName:
    Type: String
    Default: bemac-meeting-system

  AzureOpenAIApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: "Azure OpenAI API Key (leave empty to keep existing value)"

  DatabaseUrl:
    Type: String
    NoEcho: true
    Default: ""
    Description: "PostgreSQL Database URL (leave empty to keep existing value)"

  AwsAccessKeyId:
    Type: String
    NoEcho: true
    Default: ""
    Description: "AWS Access Key ID for S3 access (leave empty to keep existing value)"

  AwsSecretAccessKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: "AWS Secret Access Key for S3 access (leave empty to keep existing value)"

### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Resources                                                                                     ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Resources:
  # ----------------------------------------------------------------------------- #
  # Secrets Manager - Unified Application Secrets (JSON format)
  # ----------------------------------------------------------------------------- #
  ApplicationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${CustomerName}-${ProjectName}-${Environment}-app-secrets"
      Description: "Unified application secrets for Meeting Application"
      SecretString: !Sub |
        {
          "AZURE_OPENAI_API_KEY": "${AzureOpenAIApiKey}",
          "DATABASE_URL": "${DatabaseUrl}",
          "AWS_ACCESS_KEY_ID": "${AwsAccessKeyId}",
          "AWS_SECRET_ACCESS_KEY": "${AwsSecretAccessKey}"
        }
      Tags:
        - Key: customer
          Value: !Ref CustomerName
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment
        - Key: system
          Value: !Ref SystemName


### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Outputs                                                                                       ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Outputs:
  ApplicationSecretArn:
    Description: "ARN of Unified Application Secret"
    Value: !Ref ApplicationSecret
    Export:
      Name: !Sub "${CustomerName}-${ProjectName}-${Environment}-ApplicationSecretArn"

  ApplicationSecretName:
    Description: "Name of Unified Application Secret"
    Value: !Sub "${CustomerName}-${ProjectName}-${Environment}-app-secrets"
    Export:
      Name: !Sub "${CustomerName}-${ProjectName}-${Environment}-ApplicationSecretName"