AWSTemplateFormatVersion: '2010-09-09'
Description: bemac-meeting-dev-be-alb-stacks

### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Parameters                                                                                    ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Parameters:
  CustomerName:
    Type: String
    Default: bemac

  ProjectName:
    Type: String
    Default: meeting

  Environment:
    Type: String
    Default: dev

  SystemName:
    Type: String
    Default: bemac-meeting-system

  DomainName:
    Type: String
    Default: meeting.fr-bemac.com

  Port:
    Type: Number
    Default: 8000

  ExistingPrivateHostedZoneId:
    Type: String
    Default: Z09156891XERLTU1JRZG5

### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Resources                                                                                     ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Resources:
  # ----------------------------------------------------------------------------- #
  # ALB
  # ----------------------------------------------------------------------------- #
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-be-alb
      Scheme: internal
      Type: application
      IpAddressType: ipv4
      Subnets:
        - Fn::ImportValue: aicompass-demo-PrivateSubnet1Id
        - Fn::ImportValue: aicompass-demo-PrivateSubnet2Id
      SecurityGroups:
        - Fn::ImportValue: aicompass-demo-AlbSecurityGroupId
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
        - Key: access_logs.s3.enabled
          Value: false
      Tags:
        - Key: customer
          Value: !Ref CustomerName
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment
        - Key: system
          Value: !Ref SystemName

  # ----------------------------------------------------------------------------- #
  # Listner and Rule
  # ----------------------------------------------------------------------------- #
  BackendListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !Ref Port
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            ContentType: text/plain
            StatusCode: 404
            MessageBody: "Not Found"

  BackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref BackendListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values: 
            - /*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  # ----------------------------------------------------------------------------- #
  # TargetGroup for Backend
  # ----------------------------------------------------------------------------- #
  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-backend-tg
      Port: !Ref Port
      Protocol: HTTP
      TargetType: ip
      Matcher: 
        HttpCode: 200
      VpcId:
        Fn::ImportValue: aicompass-demo-VpcId
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckPort: !Ref Port
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 60
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 4
      Tags:
        - Key: customer
          Value: !Ref CustomerName
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment
        - Key: system
          Value: !Ref SystemName

  # ----------------------------------------------------------------------------- #
  # DNS Record
  # ----------------------------------------------------------------------------- #
  AlbDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref ExistingPrivateHostedZoneId
      Name: !Sub ${DomainName}
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID


### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
### Outputs                                                                                       ###
### -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+- ###
Outputs:
  AlbArn:
    Description: ALB ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-BeAlbArn

  AlbDnsName:
    Description: ALB DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-BeAlbDnsName

  BeAlbFullName:
    Description: ALB Full Name (for CW metrics)
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
    Export:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-BeAlbFullName

  BackendTargetGroupArn:
    Description: Backend Target Group ARN
    Value: !Ref BackendTargetGroup
    Export:
      Name: !Sub ${CustomerName}-${ProjectName}-${Environment}-BeTargetGroupArn