name: Deploy Backend to EC2

# mainブランチへのpush時、またはbackend/配下の変更時に実行
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'backend/**'
  workflow_dispatch:  # 手動実行のみ有効（自動デプロイは無効化）

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/meeting-api-key.pem
          chmod 600 ~/.ssh/meeting-api-key.pem
          
          # EC2_IPが設定されているか確認
          if [ -z "${{ secrets.EC2_IP }}" ]; then
            echo "Error: EC2_IP secret is not set"
            exit 1
          fi
          
          echo "Scanning EC2 host key..."
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts 2>&1 || echo "Warning: ssh-keyscan failed, will use StrictHostKeyChecking=no"
          
          # SSH接続オプションを設定（ホスト鍵チェックを無効化）
          echo "Host ${{ secrets.EC2_IP }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config

      - name: Deploy backend files to EC2
        run: |
          cd backend
          scp -i ~/.ssh/meeting-api-key.pem -o StrictHostKeyChecking=no -r \
            app/ run.py requirements.txt \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:~/backend/

      - name: Restart backend service
        run: |
          ssh -i ~/.ssh/meeting-api-key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            "sudo systemctl restart meeting-api"

      - name: Wait for service to start
        run: sleep 5

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/meeting-api-key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            "curl -f http://localhost:8000/health || exit 1"

      - name: Cleanup
        if: always()
        run: rm -f ~/.ssh/meeting-api-key.pem

